Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,53 +1,139 @@
+defaults: &defaults
+  #working_directory: ./circleci
+  docker:
+    - image: circleci/node:8
+
 version: 2
 jobs:
-  build:
-    working_directory: ~/mern-starter
-    # The primary container is an instance of the first image listed. The job's commands run in this container.
-    docker:
-      - image: circleci/node:4.8.2-jessie
-    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
-      - image: mongo:3.4.4-jessie
+  prepare:
+    <<: *defaults
     steps:
       - checkout
-      - run:
-          name: Update npm
-          command: 'sudo npm install -g npm@latest'
+      # Download and cache dependencies
       - restore_cache:
-          key: dependency-cache-{{ checksum "package.json" }}
-      - run:
-          name: Install npm wee
-          command: npm install
+          keys:
+          - v1-dependencies-{{ checksum "package.json" }}
+      - run: npm install
       - save_cache:
-          key: dependency-cache-{{ checksum "package.json" }}
           paths:
             - node_modules
-  test:
-    docker:
-      - image: circleci/node:4.8.2-jessie
-      - image: mongo:3.4.4-jessie
+          key: v1-dependencies-{{ checksum "package.json" }}
+      - persist_to_workspace:
+          root: .
+          paths:
+            - node_modules
+  build:
+    <<: *defaults
     steps:
       - checkout
-      - run:
-          name: Test
-          command: npm test
-      - run:
-          name: Generate code coverage
-          command: './node_modules/.bin/nyc report --reporter=text-lcov'
-      - store_artifacts:
-          path: test-results.xml
-          prefix: tests
-      - store_artifacts:
-          path: coverage
-          prefix: coverage
+      - attach_workspace:
+          at: .
+      - run: npm run build
+      - persist_to_workspace:
+          root: .
+          paths:
+            - build
+  tu:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run: npm run test
+  e2e:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run: npm run test
+  lint:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run: npm run lint
+  deploy-github:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - deploy:
+          name: Deploy to GitHub Pages
+          command: |
+              set -e
+
+              remote=$(git config remote.origin.url)
+
+              if [ ! -d "build" ]
+              then
+                  echo "build folder not found"
+                  exit 1
+              fi
+
+              mkdir gh-pages-branch
+              cd gh-pages-branch
+              git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
+              git config --global user.name "$GH_NAME" > /dev/null 2>&1
+              git init
+              git remote add --fetch origin "$remote"
+
+              if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
+              then
+                  git checkout gh-pages
+                  git rm -rf .
+              else
+                  git checkout --orphan gh-pages
+              fi
+
+              cp -a "../build/." .
+
+              git add -A
+              git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
+              git push --force --quiet origin gh-pages > /dev/null 2>&1
+
+              cd ..
+              rm -rf gh-pages-branch
+
+              echo "Finished GitHub pages Deployment!"
+
+  deploy-prod:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - deploy:
+          name: Deploy to Production
+          command: |
+              echo "iooooooo"
+
 
 workflows:
   version: 2
-  build_and_test:
+  build_accept_deploy:
     jobs:
-      - build
-      - test:
+      - prepare
+      - lint:
+          requires:
+            - prepare
+      - build:
+          requires:
+            - lint
+      - tu:
           requires:
             - build
-          filters:
-            branches:
-              only: master
+      - e2e:
+          requires:
+            - build
+      - deploy-github:
+          requires:
+            - tu
+            - e2e
+      - deploy-prod:
+          type: approval
+          requires:
+            - tu
+            - e2e
